<b> Python interview question - Hands on practice 

# Hands on practice

In [69]:
# 1.How do you get a list of all the keys from a dictionary
my_dict = {'ai':'artificial intelligence', 'ml':'machine learning','dl':'deep learning','ds': 'data science',
           'nlp':'natural language processing','tsa':'time series analyzes'}
my_list = list(my_dict.keys())    #type conversion using list()
print(my_list)

['ai', 'ml', 'dl', 'ds', 'nlp', 'tsa']


In [71]:
# 2. Write a program to filter out the number divisible by 3 from a tuple using lambda function
numbers=(34,2,5,27,21,6,18,59,36,30,99,39,24,15,67,86)
num_divisible_by_3 = list(filter(lambda x: x%3==0, numbers ))    #syntax: filter(functionName, iterable)
print(num_divisible_by_3)

[27, 21, 6, 18, 36, 30, 99, 39, 24, 15]


In [74]:
# 7.How can you delete a file in Python?
import os    # os library used to interact with Operating system and allows us to perform operations in it 
os.remove("sampleFile.txt")

In [73]:
# 11.Write a code snippet to reverse an array
arr2=[3,4,56,77,78,9]
arr2.reverse()
arr2

[9, 78, 77, 56, 4, 3]

In [83]:
# 12.Write a code snippet to get an element, delete an element, and update an element in an array.
import array 
myarr = array.array('i',[1,2,3,4,5,6])
print("array : " , myarr)
print("get a element (index 3): ", myarr[3])
myarr.remove(5)   # by element
print("delete an element (5 from arr) :  ", myarr)
del myarr[4]  #  by index
print("delete an element (6 from arr) :  ", myarr)
myarr[3] = 876
print("update an element: (at index 3):  ",myarr)

array :  array('i', [1, 2, 3, 4, 5, 6])
get a element (index 3):  4
delete an element (5 from arr) :   array('i', [1, 2, 3, 4, 6])
delete an element (6 from arr) :   array('i', [1, 2, 3, 4])
update an element: (at index 3):   array('i', [1, 2, 3, 876])


In [35]:
# 13. Write a code snippet to generate the square of every element of a list.
list_1 = [1,2,3,4,5,6,7,8,9,10]
list_1_square = list(map(lambda x: x**2, list_1))
print("square of every element of a list: ",list_1_square)

square of every element of a list:  [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [33]:
# 27.How to use list comprehension to simplify code that generate a list of square for all even number from 0 to 10?
even_squares = [x**2 for x in range(0,11) if x%2==0]
print("list of square for all even number from 0 to 10 : ", even_squares)

list of square for all even number from 0 to 10 :  [0, 4, 16, 36, 64, 100]


In [34]:
# 29.Convert string to list
myString = "hello"
converted_list = list(myString)
print("Convert string to list: ",converted_list)

Convert string to list:  ['h', 'e', 'l', 'l', 'o']


In [63]:
# 35.Prime
def isPrime(num):
    if num<2:
        return False
    for i in range(2,int(num**0.5)+1):
        if num%i==0:
            return False
    return True 

num = int(input("Enter the number to find prime or not: "))
if isPrime(num):
    print(f"{num} is Prime Number")
else:
    print(f"{num} is Not a Prime Number")

Enter the number to find prime or not:  953


953 is Prime Number


In [66]:
# 36.Factorial
def factorial(num):
    if num==0: # base case
        return 1
    return num * factorial(num-1)  #recursive case
factorial(5)

120

In [75]:
# 37.Square root
import math
print(math.sqrt(25))

5.0


In [79]:
# 38.Leap year
def isLearYear(year):
    return (year%4==0 and year%100!=0) or (year%400==0)
year = int(input("Enter the year to find leap year or not: "))
if isLearYear(year):
    print(f"{year} is Leap Year")
else:
    print(f"{year} is Not a  Leap Year")

Enter the year to find leap year or not:  2025


2025 is Not a  Leap Year


In [107]:
# 39.Palindrome
def isPalindrome(string):
    reversed_str=""
    for i in string:
        reversed_str = i+ reversed_str
    return string == reversed_str
string = (input("Enter the string to find Palindrome or not: "))
if isPalindrome(string):
    print(f"{string} is Palindrome")
else:
    print(f"{string} is Not a  Palindrome")

Enter the string to find Palindrome or not:  hello world


hello world is Not a  Palindrome


In [89]:
# 64.How would you reverse a numpy array?
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(" reverse a numpy array: ",arr[::-1])

 reverse a numpy array:  [6 5 4 3 2 1]


# Map vs filter vs zip

In [34]:
# map
# example 1 -- 2 iterables
num_list = [2,4,6,8]
square_numList = list(map(lambda x: x**2, num_list))
print("map example1 (square of even numbers): ",square_numList)

# example 2 -- multiple iterables
num_list = [1,3,5,7]
powOf = [3,3,3,3]
square_numList = list(map(lambda x,y: x**y, num_list,powOf))    #syntax:    map(function, iterable1, iterable2 , .......)     - 2 or more iterables
print("map example2 (cube of odd number): ",square_numList)

map example1 (square of even numbers):  [4, 16, 36, 64]
map example2 (cube of odd number):  [1, 27, 125, 343]


In [108]:
# zip
# example 1 -- multiple iterables
a=[324,34,34,3,43]
b=[33,3,3,3]
c=[4.4,45,6,6]
res = set(zip(a,b,c))
print("zip object: ", zip(a,b,c))
print("zip example 1 (zipping 3 iterables) : ",res)

# example 2    -- 2 iterables
name=["john","elsa","kavi"]
role=["HR","Manager","Employee"]
result=list(zip(name, role))     #syntax:   zip(iterable1,iterable2, .....)      - 2 or more iterables
print("zip example 2 (merging 2 iterables): ",result)

zip object:  <zip object at 0x000001ADA9BE4C40>
zip example 1 (zipping 3 iterables) :  {(3, 3, 6), (34, 3, 6), (324, 33, 4.4), (34, 3, 45)}
zip example 2 (merging 2 iterables):  [('john', 'HR'), ('elsa', 'Manager'), ('kavi', 'Employee')]


# python basics

In [38]:
# check type of variable 
a = 44.4
type(a)

float

In [39]:
# convert number string into int 
num="2354"
converted_int = int(num)
converted_int

2354

In [85]:
# Python concepts

In [109]:
""" 
python data types:- 
int, float, bool, string   
list, tuple, set, dict  

mutable - list , dict, set
immutable - tuple, string, int, float

range-- python version 3 
xrange-- python version 2 

module -- single python file 
package -- a directoty contains multiple modules

list -- different data type , collection of items
array -- same data type,  used for performing numerical operations in array

benefits of functions --> code reusability, modular code structure, easier to debug, maintain and test

data structures --> list, tuple,  dictionary, set , array, string

built in types --> int, float, string, boolean, None type, list, set, tuple, dictionary

oops in python --> class, object, inheritence, abstraction, polymorphism, encapsulation

list -- mutable, dynamic size, slower
tuple -- immutable, fixed size, faster

set:
- unordered collection of unique elements
- created using set() function or {1,2,3}
- useful when representing data's without duplicates (unique data's )
- can perform mathematical set operations like: union(), intersection(), difference(), symmentric_difference()




"""

" \npython data types:- \nint, float, bool, string   \nlist, tuple, set, dict  \n\nmutable - list , dict, set\nimmutable - tuple, string, int, float\n\nrange-- python version 3 \nxrange-- python version 2 \n\nmodule -- single python file \npackage -- a directoty contains multiple modules\n\nlist -- different data type , collection of items\narray -- same data type,  used for performing numerical operations in array\n\nbenefits of functions --> code reusability, modular code structure, easier to debug, maintain and test\n\ndata structures --> list, tuple,  dictionary, set , array, string\n\nbuilt in types --> int, float, string, boolean, None type, list, set, tuple, dictionary\n\noops in python --> class, object, inheritence, abstraction, polymorphism, encapsulation\n\nlist -- mutable, dynamic size, slower\ntuple -- immutable, fixed size, faster\n\nset:\n- unordered collection of unique elements\n- created using set() function or {1,2,3}\n- useful when representing data's without duplic

# list 

In [120]:
# access list element 
list1=[33,456,2,5]
list1[3]

5

In [121]:
# deleting an element from a list.
# using remove   ---- specify the element
list1.remove(2)

In [122]:
list1

[33, 456, 5]

In [123]:
# using pop --- specify index
list1.pop(1)

456

In [124]:
list1

[33, 5]

In [125]:
del list1[0]   # --- delete using del keyword (by passing index of the element)

In [126]:
list1

[5]

In [127]:
# delete an entire list.
del list1

In [69]:
list1     # thorws error -- as the list is deleted 

NameError: name 'list1' is not defined

In [14]:
x = ['a','b']
print((list(map(set,x))))
print("output of following: ", len(list(map(list,x))))

[{'a'}, {'b'}]
output of following:  2


# array 

In [129]:
arr2=[3244,434,4]
arr2 * 2   #list

[3244, 434, 4, 3244, 434, 4]

In [85]:
import array
a = array.array('i',[2,3,4,5])
a

array('i', [2, 3, 4, 5])

In [90]:
a * 2      # array module

array('i', [2, 3, 4, 5, 2, 3, 4, 5])

In [87]:
import numpy as np 
n = np.array([2,2,2,2])
n

array([2, 2, 2, 2])

In [91]:
n*2      #numpy array

array([4, 4, 4, 4])

In [16]:
#array module 
# create array
import array
myarray_f = array.array('f',[3.5,67.7,8.56,9.3])  #less precision
print(myarray_f)

array('f', [3.5, 67.69999694824219, 8.5600004196167, 9.300000190734863])


In [30]:
import array
myarray_d = array.array('d',[3.5,67.7,8.56,9.3])  #higher precision
print(myarray_d)

array('d', [3.5, 67.7, 8.56, 9.3])


In [31]:
# array access 
myarray_d[3]

9.3

In [32]:
# update array
myarray_d[3] = 456.45
myarray_d

array('d', [3.5, 67.7, 8.56, 456.45])

In [33]:
# append array 
myarray_d.append(333.3333)
myarray_d

array('d', [3.5, 67.7, 8.56, 456.45, 333.3333])

# Numpy array

In [130]:
# numpy array
import numpy as np 
# create --  numpy array  -- 1d arr
arr= np.array([34.2,53.44,9.44,67.44,89.22])
arr

array([34.2 , 53.44,  9.44, 67.44, 89.22])

In [131]:
# access 1d arr
arr[2]

np.float64(9.44)

In [132]:
# create -  n dimensional array   (2d arr)
nd_arr= np.array([[34,53,9,67,89],[2,3,4,56,6]])
nd_arr

array([[34, 53,  9, 67, 89],
       [ 2,  3,  4, 56,  6]])

In [61]:
nd_arr[1][3]   #access 2d arr

np.int64(56)

In [63]:
# performing operations 
# 1d arr 
print(arr)
print(arr * 2)

[34 53  9 67 89]
[ 68 106  18 134 178]


In [68]:
# performing operations 
# 2d arr 
print(nd_arr)
print(nd_arr * 10)

[[34 53  9 67 89]
 [ 2  3  4 56  6]]
[[340 530  90 670 890]
 [ 20  30  40 560  60]]


# ordered dict

In [92]:
from collections import OrderedDict
od = OrderedDict()
od['class1']='maths'
od['class2']='cs'
od

OrderedDict([('class1', 'maths'), ('class2', 'cs')])

In [133]:
# dict -- checking equality    (dict only checks the keys and values)
{'class1':'maths','class2':'cs'} == {'class2':'cs', 'class1':'maths'}

True

In [134]:
# ordered dict -- checking equality    
from collections import OrderedDict
od1 = OrderedDict([('class1', 'maths'), ('class2', 'cs')])
od2 = OrderedDict([ ('class2', 'cs'), ('class1', 'maths')])
od1 == od2   # because it checks the order    (Ordered dict --> checks the keys and values  + Thier Order)

False

In [109]:
od3 = OrderedDict([('a',11),('b',22),('c',33)])
od3

OrderedDict([('a', 11), ('b', 22), ('c', 33)])

In [110]:
# changing the order - move to end
od3.move_to_end('b')
od3

OrderedDict([('a', 11), ('c', 33), ('b', 22)])

In [111]:
# changing the order - move to begining
od3.move_to_end('c', last=False)   
od3

OrderedDict([('c', 33), ('a', 11), ('b', 22)])

In [19]:
#### -- need to learn 
# Pandas 
""" 49 50 51 55 56 57 58 59 60 61 62 67 68  """
# genetic algorithm ---> 65 

' 49 50 51 55 56 57 58 59 60 61 62 67 68  '

In [76]:
# Decimal to binary 
def d_b(num):
    if num==1:
        return "1"
    quotient = num//2  
    remainder = num%2
    return  d_b(quotient) + str(remainder)

d_b(4)
        

'100'

In [50]:
# find longest word in string 
""" Approach 1 """  # O(n)
s = " hello i am a python program used to write code"
separated_words = s.strip().split(' ')       # separate the words
word_len = {}
for word in separated_words:
    word_len[len(word)] = word    # find the length of each word 
word_len[max(word_len.keys())]    # return the word which has maximum length 

'program'

In [51]:
""" Approach 2 """  # O(2n)
s = " hello i am a python program used to write code"
separated_words = s.strip().split(' ') 
l =[]
for i in separated_words:
    l.append(len(i))
max(l)
for i in separated_words:
    if len(i) == 7:
        print(i)

program


In [56]:
""" Best approach """  # using max() function 
s = " hello i am a python program used to write code"
max(s.strip().split(' '), key=len)

'program'

In [80]:
#  find the word is anagram
def isAnagram(w1, w2):
    if sorted(w1.lower()) == sorted(w2.lower()):   # sort by lower case 
        return True
    else:
        return False
isAnagram('rAce','care')


True